version: '3.9'

services:
  app:
    container_name: nest_backend
    image: nest_backend:1.0
    build:
      context: .
      args:
        - NODE_ENV=development
      # target: production
      dockerfile: ./Dockerfile
    command: npm run start:debug
    env_file: .env
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - app-network
    restart: unless-stopped
  redis-ui:
    container_name: redis-ui
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
